# Generated by Django 4.2.6 on 2023-10-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_reservation', models.DateField(auto_now_add=True, verbose_name='Дата брони')),
                ('start_reservation', models.DateField(verbose_name='Начало брони')),
                ('end_reservation', models.DateField(verbose_name='Конец брони')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.room', verbose_name='Номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Забронированная комната',
                'verbose_name_plural': 'Забронированные комнаты',
            },
        ),
    ]
